/**
 * Build every brand raster from the single geometry source.
 *
 * Run: npm run brand:build
 *
 * Writes public/brand/gt-monogram.svg from src/lib/brand/monogram.json, then
 * rasterises it to the sizes the identity actually has to survive.
 *
 * The 16px render is the one that matters — if the mark does not read there it
 * does not read in a browser tab, and the geometry needs changing rather than
 * the export settings. gt-16-magnified.png exists so that call can be made by
 * eye, on the real pixel grid, instead of assumed.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ROOT = process.cwd();
const OUT = path.join(ROOT, "public", "brand");
const SVG_PATH = path.join(OUT, "gt-monogram.svg");

const INK = "#0A0F14";
const CHALK = "#F4F3EF";
const BONE = "#E6E3DA";

const geometry = JSON.parse(
  await readFile(path.join(ROOT, "src", "lib", "brand", "monogram.json"), "utf8"),
);

/**
 * The drawn mark sits tight in its 64-unit grid, which is what inline use
 * wants — surrounding layout controls the spacing. An app icon is the opposite
 * case: it is cropped to a square by the platform, so it needs breathing room
 * baked in and the mark optically centred rather than grid-centred.
 */
const ICON_VIEWBOX = "-10.5 -10 83 83";

/**
 * @param {string} stroke
 * @param {string} [viewBox]
 */
function buildSvg(stroke, viewBox = geometry.viewBox) {
  const paths = geometry.paths.map((p) => `  <path d="${p.d}"/>`).join("\n");
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="64" height="64"`,
    `     fill="none" stroke="${stroke}" stroke-width="${geometry.strokeWidth}" stroke-linecap="butt">`,
    "  <title>Guard Theory</title>",
    paths,
    "</svg>",
    "",
  ].join("\n");
}

await mkdir(OUT, { recursive: true });
await writeFile(SVG_PATH, buildSvg(CHALK), "utf8");
console.log("  gt-monogram.svg");

const TARGETS = [
  { name: "gt-16", size: 16, bg: INK, fg: CHALK },
  { name: "gt-32", size: 32, bg: INK, fg: CHALK },
  { name: "gt-64", size: 64, bg: INK, fg: CHALK },
  { name: "gt-180", size: 180, bg: INK, fg: CHALK },
  { name: "gt-512", size: 512, bg: INK, fg: CHALK },
  { name: "gt-512-ink-on-bone", size: 512, bg: BONE, fg: INK },
];

for (const { name, size, bg, fg } of TARGETS) {
  await sharp(Buffer.from(buildSvg(fg, ICON_VIEWBOX)), { density: 384 })
    .resize(size, size, { fit: "contain", background: bg })
    .flatten({ background: bg })
    .png({ compressionLevel: 9 })
    .toFile(path.join(OUT, `${name}.png`));
  console.log(`  ${name}.png  ${size}×${size}  ${fg} on ${bg}`);
}

await sharp(path.join(OUT, "gt-16.png"))
  .resize(320, 320, { kernel: "nearest" })
  .png({ compressionLevel: 9 })
  .toFile(path.join(OUT, "gt-16-magnified.png"));
console.log("  gt-16-magnified.png  16px render at 20× nearest-neighbour");

// The icons Next.js picks up by file convention. Written from the same geometry
// so the browser tab, the home-screen icon and the site all show one mark.
const APP = path.join(ROOT, "src", "app");

await writeFile(path.join(APP, "icon.svg"), buildSvg(CHALK, ICON_VIEWBOX), "utf8");
console.log("  src/app/icon.svg");

await sharp(Buffer.from(buildSvg(CHALK, ICON_VIEWBOX)), { density: 384 })
  .resize(180, 180, { fit: "contain", background: INK })
  .flatten({ background: INK })
  .png({ compressionLevel: 9 })
  .toFile(path.join(APP, "apple-icon.png"));
console.log("  src/app/apple-icon.png  180×180");

await writeFile(
  path.join(OUT, "README.md"),
  [
    "# Brand rasters",
    "",
    "Generated by `npm run brand:build` from `src/lib/brand/monogram.json`.",
    "Do not edit these files by hand — change the geometry and re-run.",
    "",
    "`gt-16-magnified.png` is the 16px render blown up with nearest-neighbour",
    "sampling. It exists so the favicon can be judged on its real pixel grid.",
    "",
  ].join("\n"),
  "utf8",
);

// --- Open Graph card -------------------------------------------------------
//
// Generated here and committed as a static PNG rather than rendered at request
// time. A link preview that depends on a font fetch at build time is a link
// preview that silently breaks; this one is a file.
//
// 1200x630 is the size every messaging app and social network crops from.

const OG_W = 1200;
const OG_H = 630;

function ogSvg() {
  const mark = geometry.paths
    .map((p) => `<path d="${p.d}"/>`)
    .join("");

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${OG_W}" height="${OG_H}" viewBox="0 0 ${OG_W} ${OG_H}">
  <rect width="${OG_W}" height="${OG_H}" fill="${INK}"/>

  <!-- plate field, echoing the drawings on the site -->
  <rect x="56" y="56" width="${OG_W - 112}" height="${OG_H - 112}" fill="none" stroke="#3A444F" stroke-width="1.5"/>
  <g stroke="#3A444F" stroke-width="1.5">
    <line x1="76" y1="76" x2="96" y2="76"/><line x1="76" y1="66" x2="76" y2="86"/>
    <line x1="${OG_W - 96}" y1="76" x2="${OG_W - 76}" y2="76"/><line x1="${OG_W - 76}" y1="66" x2="${OG_W - 76}" y2="86"/>
    <line x1="76" y1="${OG_H - 76}" x2="96" y2="${OG_H - 76}"/><line x1="76" y1="${OG_H - 86}" x2="76" y2="${OG_H - 66}"/>
    <line x1="${OG_W - 96}" y1="${OG_H - 76}" x2="${OG_W - 76}" y2="${OG_H - 76}"/><line x1="${OG_W - 76}" y1="${OG_H - 86}" x2="${OG_W - 76}" y2="${OG_H - 66}"/>
  </g>

  <!-- monogram -->
  <g transform="translate(112, 132) scale(2.6)" fill="none" stroke="${CHALK}"
     stroke-width="${geometry.strokeWidth}" stroke-linecap="butt">${mark}</g>

  <text x="112" y="392" font-family="Arial Narrow, Arial, sans-serif" font-size="104"
        font-weight="700" letter-spacing="2" fill="${CHALK}">GUARD THEORY</text>

  <text x="116" y="452" font-family="Arial, sans-serif" font-size="34" fill="#8A95A1">
    No-gi grappling apparel, and a technical study of the guard.
  </text>

  <line x1="112" y1="504" x2="248" y2="504" stroke="#E3C74B" stroke-width="4"/>

  <text x="112" y="556" font-family="Consolas, monospace" font-size="26" letter-spacing="1" fill="#8A95A1">
    POSITION BEFORE SUBMISSION. SYSTEMS BEFORE CHAOS.
  </text>
</svg>`;
}

await sharp(Buffer.from(ogSvg()))
  .png({ compressionLevel: 9 })
  .toFile(path.join(APP, "opengraph-image.png"));
console.log("  src/app/opengraph-image.png  1200×630");

await writeFile(
  path.join(APP, "opengraph-image.alt.txt"),
  "Guard Theory — no-gi grappling apparel, and a technical study of the guard.\n",
  "utf8",
);
console.log("  src/app/opengraph-image.alt.txt");
