/**
 * Build every brand raster from the single geometry source.
 *
 * Run: npm run brand:build
 *
 * Writes public/brand/gt-monogram.svg from src/lib/brand/monogram.json, then
 * rasterises it to the sizes the identity actually has to survive.
 *
 * The 16px render is the one that matters — if the mark does not read there it
 * does not read in a browser tab, and the geometry needs changing rather than
 * the export settings. gt-16-magnified.png exists so that call can be made by
 * eye, on the real pixel grid, instead of assumed.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ROOT = process.cwd();
const OUT = path.join(ROOT, "public", "brand");
const SVG_PATH = path.join(OUT, "gt-monogram.svg");

const INK = "#0A0F14";
const CHALK = "#F4F3EF";
const BONE = "#E6E3DA";

const geometry = JSON.parse(
  await readFile(path.join(ROOT, "src", "lib", "brand", "monogram.json"), "utf8"),
);

/**
 * The drawn mark sits tight in its 64-unit grid, which is what inline use
 * wants — surrounding layout controls the spacing. An app icon is the opposite
 * case: it is cropped to a square by the platform, so it needs breathing room
 * baked in and the mark optically centred rather than grid-centred.
 */
const ICON_VIEWBOX = "-10.5 -10 83 83";

/**
 * @param {string} stroke
 * @param {string} [viewBox]
 */
function buildSvg(stroke, viewBox = geometry.viewBox) {
  const paths = geometry.paths.map((p) => `  <path d="${p.d}"/>`).join("\n");
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="64" height="64"`,
    `     fill="none" stroke="${stroke}" stroke-width="${geometry.strokeWidth}" stroke-linecap="butt">`,
    "  <title>Guard Theory</title>",
    paths,
    "</svg>",
    "",
  ].join("\n");
}

await mkdir(OUT, { recursive: true });
await writeFile(SVG_PATH, buildSvg(CHALK), "utf8");
console.log("  gt-monogram.svg");

const TARGETS = [
  { name: "gt-16", size: 16, bg: INK, fg: CHALK },
  { name: "gt-32", size: 32, bg: INK, fg: CHALK },
  { name: "gt-64", size: 64, bg: INK, fg: CHALK },
  { name: "gt-180", size: 180, bg: INK, fg: CHALK },
  { name: "gt-512", size: 512, bg: INK, fg: CHALK },
  { name: "gt-512-ink-on-bone", size: 512, bg: BONE, fg: INK },
];

for (const { name, size, bg, fg } of TARGETS) {
  await sharp(Buffer.from(buildSvg(fg, ICON_VIEWBOX)), { density: 384 })
    .resize(size, size, { fit: "contain", background: bg })
    .flatten({ background: bg })
    .png({ compressionLevel: 9 })
    .toFile(path.join(OUT, `${name}.png`));
  console.log(`  ${name}.png  ${size}×${size}  ${fg} on ${bg}`);
}

await sharp(path.join(OUT, "gt-16.png"))
  .resize(320, 320, { kernel: "nearest" })
  .png({ compressionLevel: 9 })
  .toFile(path.join(OUT, "gt-16-magnified.png"));
console.log("  gt-16-magnified.png  16px render at 20× nearest-neighbour");

// The icons Next.js picks up by file convention. Written from the same geometry
// so the browser tab, the home-screen icon and the site all show one mark.
const APP = path.join(ROOT, "src", "app");

await writeFile(path.join(APP, "icon.svg"), buildSvg(CHALK, ICON_VIEWBOX), "utf8");
console.log("  src/app/icon.svg");

await sharp(Buffer.from(buildSvg(CHALK, ICON_VIEWBOX)), { density: 384 })
  .resize(180, 180, { fit: "contain", background: INK })
  .flatten({ background: INK })
  .png({ compressionLevel: 9 })
  .toFile(path.join(APP, "apple-icon.png"));
console.log("  src/app/apple-icon.png  180×180");

await writeFile(
  path.join(OUT, "README.md"),
  [
    "# Brand rasters",
    "",
    "Generated by `npm run brand:build` from `src/lib/brand/monogram.json`.",
    "Do not edit these files by hand — change the geometry and re-run.",
    "",
    "`gt-16-magnified.png` is the 16px render blown up with nearest-neighbour",
    "sampling. It exists so the favicon can be judged on its real pixel grid.",
    "",
  ].join("\n"),
  "utf8",
);
