import type { MetadataRoute } from "next";
import { SITE_DESCRIPTION, SITE_NAME } from "@/lib/site";

/**
 * The web app manifest, which is what gives the mark a home on a phone's home
 * screen and in a desktop install prompt.
 *
 * `maskable` is a separate file rather than a second purpose on the same one:
 * Android crops a maskable icon to whatever shape the launcher uses and may
 * keep as little as the inner 80%, so the mark in that file is inset to the safe
 * zone. Declaring one image as both `any` and `maskable` means it is either
 * cropped into or floating in a tile, depending on which platform is asking.
 *
 * Icons are generated by `npm run brand:build` from the same vector source as
 * the header and the favicon.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${SITE_NAME} — No-gi grappling apparel`,
    short_name: SITE_NAME,
    description: SITE_DESCRIPTION,
    start_url: "/",
    display: "standalone",
    background_color: "#1B1725",
    theme_color: "#1B1725",
    icons: [
      { src: "/brand/gt-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/brand/gt-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/brand/gt-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
